# -*- mode: ruby -*-
NUMBER_OF_WEBSERVERS = 2          # Maximum is 9 with the defined ip assignments
CPU = 1
MEMORY = 512
ADMIN_USER = "vagrant"
ADMIN_PASSWORD = "vagrant"
VM_VERSION= "ubuntu/trusty64"
#VM_VERSION= "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
VAGRANT_VM_PROVIDER = "virtualbox"

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    # create some web servers
    # https://docs.vagrantup.com/v2/vagrantfile/tips.html
    (1..NUMBER_OF_WEBSERVERS).each do |i|
        config.vm.define "web#{i}" do |node|
            node.vm.box = VM_VERSION
            node.vm.hostname = "web#{i}"
            node.vm.network :private_network, ip: "10.0.15.2#{i}"
            node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
            node.vm.provider VAGRANT_VM_PROVIDER do |vb|
                vb.memory = MEMORY
            end
            node.vm.provision "chef_zero" do |chef|
                chef.cookbooks_path = "cookbooks"
                chef.roles_path = "roles"
                chef.nodes_path = "nodes"
                chef.add_role "web"
            end
        end
    end


    # create load balancer
    config.vm.define "load_balancer" do |lb_config|
        lb_config.vm.box = VM_VERSION
        lb_config.vm.hostname = "lb"
        lb_config.vm.network :private_network, ip: "10.0.15.11"
        lb_config.vm.network "forwarded_port", guest: 80, host: 8011
        lb_config.vm.provider VAGRANT_VM_PROVIDER do |vb|
            vb.memory = MEMORY
        end
        lb_config.vm.provision "chef_zero" do |chef|
            chef.cookbooks_path = "cookbooks"
            chef.roles_path = "roles"
            chef.nodes_path = "nodes"
            chef.add_role "lb"
            chef.json = { :lb => { :num_servers => NUMBER_OF_WEBSERVERS } }
        end
    end
end
